stages:
  data_ingestion:
    cmd: python src/MalariaCellHistopathologyClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MalariaCellHistopathologyClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset

  model_training:
    cmd: python src/MalariaCellHistopathologyClassification/pipeline/stage_02_model_trainer.py
    deps:
      - src/MalariaCellHistopathologyClassification/pipeline/stage_02_model_trainer.py
      - artifacts/data_ingestion/dataset
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/training/Malaria_cell_TF.h5

  model_evaluation:
    cmd: python src/MalariaCellHistopathologyClassification/pipeline/stage_03_model_evaluator.py
    deps:
     - src/MalariaCellHistopathologyClassification/pipeline/stage_03_model_evaluator.pyy
     - artifacts/data_ingestion/dataset
     - config/config.yaml
     - params.yaml
     - artifacts/training/Malaria_cell_TF.h5
    metrics:
      - scores.json:
          cache: False