BATCH_SIZE: 32
IMG_SIZE: (224,224)
IMG_SHAPE: IMG_SIZE + (3,)
BASE_LEARNING_RATE: 0.0001
EPOCH: 1
OPTIMIZER: tf.keras.optimizers.Adam(learning_rate=BASE_LEARNING_RATE)
LOSS: tf.keras.losses.BinaryCrossentropy(from_logits=True)
METRICS: [tf.keras.metrics.BinaryAccuracy(threshold=0, name='accuracy')]
BASE_MODEL: tf.keras.applications.VGG19(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')